name: Lint

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run rustfmt
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: clechasseur/rs-clippy-check@v3

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        run: |
          # Setup latest jq
          curl -Lo jq https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64
          chmod +x jq
          # Setup cargo msrv
          cargo_msrv="cargo-msrv-x86_64-unknown-linux-gnu-v0.16.0-beta.22"
          curl -Lo "$cargo_msrv".tgz https://github.com/foresterre/cargo-msrv/releases/download/v0.16.0-beta.22/"$cargo_msrv".tgz
          tar -xvf "$cargo_msrv".tgz
          mv "$cargo_msrv"/cargo-msrv ./
      - name: Detect MSRV changes
        run: |
          defined_msrv="$(./cargo-msrv show --output-format json 2>&1 | ./jq -r '.result.version' | tail -n 1)"
          dependency_msrv="$(./cargo-msrv list --output-format json 2>&1 | ./jq -r '.result.list.[0].msrv' | tail -n 1)"
          echo "defined_msrv=$defined_msrv"
          echo "dependency_msrv=$dependency_msrv"
          if [ "$defined_msrv" != "$dependency_msrv" ]; then
            echo "::error::MSRV changed | defined: '$defined_msrv', absolute: '$dependency_msrv'"
            exit 1
          fi

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  renovate-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.0
