name: tarpaulin

on:
  pull_request:
    paths:
      - '**/*.lock'
      - '**/*.rs'
      - '**/*.toml'
      - '**/tarpaulin.yml'

permissions:
  pull-requests: write

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: cargo
        uses: taiki-e/install-action@v2.18.16
        with:
          tool: cargo-tarpaulin

      - name: python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11

      - name: checkout
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: requirements
        run: echo pycobertura >> requirements.txt

      - name: dependencies
        uses: py-actions/py-dependency-install@v4.0.0

      - name: tarpaulin
        run: |
          cargo tarpaulin \
          && echo '```' >> message.txt \
          && pycobertura show cobertura.xml >> message.txt \
          && echo '```' >> message.txt

      - name: comment
        uses: thollander/actions-comment-pull-request@v2.4.2
        with:
          comment_tag: tarpaulin
          filePath: message.txt
