name: tarpaulin

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  coverage:
    name: coverage
    outputs:
      cobertura: ${{ steps.tarpaulin.outputs.cobertura }}
    runs-on: ubuntu-latest
    steps:
      - name: cargo
        uses: taiki-e/install-action@v2.8.0
        with:
          tool: cargo-tarpaulin

      - name: python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.11

      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: requirements
        run: echo pycobertura >> requirements.txt

      - name: dependencies
        uses: py-actions/py-dependency-install@v4.0.0

      - id: tarpaulin
        name: tarpaulin
        run: |
          cargo tarpaulin
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "text<<$EOF" >> $GITHUB_OUTPUT
          pycobertura show cobertura.xml  >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          comment_tag: tarpaulin
          message: |
            ```
            ${{ steps.tarpaulin.outputs }}
            ```
