name: tarpaulin

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: cargo
        uses: taiki-e/install-action@v2.8.0
        with:
          tool: cargo-tarpaulin

      - name: python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.11

      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: requirements
        run: echo pycobertura >> requirements.txt

      - name: dependencies
        uses: py-actions/py-dependency-install@v4.0.0

      - name: tarpaulin
        run: |
          cargo tarpaulin \
          && echo '```' >> message.md \
          && pycobertura show cobertura.xml >> message.md \
          && echo '```' >> message.md

      - name: comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          comment_tag: tarpaulin
          filePath: message.md
